var json = {"response":{"status":"ok","userTier":"developer","total":1,"editorsPicks":[{"id":"politics/blog/live/2017/jun/22/hammond-suggests-brexit-transitional-period-could-last-up-to-four-years-politics-live","type":"liveblog","sectionId":"politics","sectionName":"Politics","webPublicationDate":"2017-06-22T10:32:20Z","webTitle":"Grenfell fire: a number of tower blocks have same flammable cladding, says Theresa May - Politics live","webUrl":"https://www.theguardian.com/politics/blog/live/2017/jun/22/hammond-suggests-brexit-transitional-period-could-last-up-to-four-years-politics-live","apiUrl":"https://content.guardianapis.com/politics/blog/live/2017/jun/22/hammond-suggests-brexit-transitional-period-could-last-up-to-four-years-politics-live","isHosted":false},{"id":"politics/2017/jun/22/dup-sees-very-good-chance-of-tory-deal-after-winning-big-concessions","type":"article","sectionId":"politics","sectionName":"Politics","webPublicationDate":"2017-06-22T08:07:08Z","webTitle":"DUP sees 'very good' chance of Tory deal after winning big concessions","webUrl":"https://www.theguardian.com/politics/2017/jun/22/dup-sees-very-good-chance-of-tory-deal-after-winning-big-concessions","apiUrl":"https://content.guardianapis.com/politics/2017/jun/22/dup-sees-very-good-chance-of-tory-deal-after-winning-big-concessions","isHosted":false},{"id":"uk-news/2017/jun/22/prince-harry-says-no-one-royal-family-wants-king-queen","type":"article","sectionId":"uk-news","sectionName":"UK news","webPublicationDate":"2017-06-22T07:11:06Z","webTitle":"Prince Harry says no one in royal family wants to be king or queen","webUrl":"https://www.theguardian.com/uk-news/2017/jun/22/prince-harry-says-no-one-royal-family-wants-king-queen","apiUrl":"https://content.guardianapis.com/uk-news/2017/jun/22/prince-harry-says-no-one-royal-family-wants-king-queen","isHosted":false}]}}


function editorsPickTest(){
  assert.isTrue(loadHeadlines(json) === "<ul><li><div>Grenfell fire: a number of tower blocks have same flammable cladding, says Theresa May - Politics live</div></li><li><div>DUP sees 'very good' chance of Tory deal after winning big concessions</div></li><li><div>Prince Harry says no one in royal family wants to be king or queen</div></li></ul>")

}

editorsPickTest();
